export enum CaseStatus {
  LEAD_CAPTURED = 'LEAD_CAPTURED',
  FRQ_INTAKE = 'FRQ_INTAKE',
  VENDOR_SELECTION = 'VENDOR_SELECTION',
  QUOTE_SENT = 'QUOTE_SENT',
  CASE_OPEN = 'CASE_OPEN',
  VENDOR_WORKING = 'VENDOR_WORKING',
  DOCUMENT_COLLECTION = 'DOCUMENT_COLLECTION',
  QA_REVIEW = 'QA_REVIEW',
  CLIENT_REVIEW = 'CLIENT_REVIEW',
  CLOSED = 'CLOSED',
}
